# Generated by Django 3.2.8 on 2021-10-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='party_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_party',
            field=models.BooleanField(default=False),
        ),
    ]
